### ISSUE TITLE
Issue in solution of exercise of I.2.1 from Foundations of Mathematics.

### ISSUE THREAD

**Issue by physxP** [kumatheworld/textbook-solutions#1]
Hi,
First of all excellent work and maybe you have moved on but I suspect there may be an issue with the solution of the exercise mentioned in the title, specifically on the fourth part on Axiom 5. In the solutions it's mentioned that Axiom 5, i,.e. the axiom of Union doesn't hold up for the domain {a,b,c} but I can't think of a reason why it won't. 

For example if we take union of all the sets then a U b U c = {a,b} = c
because a = {b}, b = {a} , c = {a,b}

Similar situation in problem 6.

**Comment by kumatheworld** [comment]
Thank you very much for your interest and thorough review.

Yes, it seems that Axiom 5 holds for every example there. Feel free to let me know if you have found another issue. Thank you for your contribution!
